CREATE SEQUENCE MESSAGE_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE TABLE MESSAGE (
  ID			NUMBER	 		PRIMARY KEY,
  NAME			VARCHAR2(50) 	NOT NULL,
  EMAIL			VARCHAR2(100) 	NOT NULL,
  MOBILE		VARCHAR2(20)	NOT NULL,
  MESSAGE		VARCHAR2(2000)	NOT NULL,
  IP_ADDRESS	VARCHAR2(50),
  CREATION_DATE TIMESTAMP		NOT NULL,
  STATUS 		VARCHAR2(50)
);

CREATE SEQUENCE DOCUMENT_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE TABLE DOCUMENT (
  ID			NUMBER			PRIMARY KEY,
  KEY			VARCHAR2(100),
  FILE_NAME		VARCHAR2(100)	NOT NULL,
  FILE_CONTENT	BLOB			NOT NULL,
  CREATION_DATE	TIMESTAMP		NOT NULL
);