DROP DATABASE IF EXISTS `sql_portfolio`;
CREATE DATABASE `sql_portfolio`;
USE `sql_portfolio`;

DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE `MESSAGE` (
  `ID` INT AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `MOBILE` VARCHAR(20) NOT NULL,
  `MESSAGE` VARCHAR(2000) NOT NULL,
  `IP_ADDRESS` VARCHAR(50),
  `CREATION_DATE` TIMESTAMP NOT NULL,
  `STATUS` VARCHAR(50),
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE `DOCUMENT` (
  `ID` INT AUTO_INCREMENT,
  `KEY` VARCHAR(100),
  `FILE_NAME` VARCHAR(100) NOT NULL,
  `FILE_CONTENT` BLOB NOT NULL,
  `CREATION_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`)
);

COMMIT;